services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r telegram-bot/requirements.txt
    startCommand: python3 telegram-bot/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: "telegram_bot"
      - key: PORT
        value: "10000"
    autoDeploy: true
